In [1]:
import pandas as pd

In [2]:
hotel_df = pd.read_csv('hotel.csv')

display(hotel_df.head())
print(hotel_df.info())

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,0,342,1,July,27,1,0,0,2,...,0,0,0,C,C,3,Transient,0.0,0,0
1,Resort Hotel,0,7,1,July,27,1,0,1,1,...,0,0,0,A,C,0,Transient,75.0,0,0
2,Resort Hotel,0,13,1,July,27,1,0,1,1,...,0,0,0,A,A,0,Transient,75.0,0,0
3,Resort Hotel,0,14,1,July,27,1,0,2,2,...,0,0,0,A,A,0,Transient,98.0,0,1
4,Resort Hotel,0,0,1,July,27,1,0,2,2,...,0,0,0,C,C,0,Transient,107.0,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85913 entries, 0 to 85912
Data columns (total 24 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   hotel                           85913 non-null  object
 1   is_canceled                     85913 non-null  int64
 2   lead_time                       85913 non-null  int64
 3   arrival_date_year               85913 non-null  int64
 4   arrival_date_month              85913 non-null  object
 5   arrival_date_week_number        85913 non-null  int64
 6   arrival_date_day_of_month       85913 non-null  int64
 7   stays_in_weekend_nights         85913 non-null  int64
 8   stays_in_week_nights            85913 non-null  int64
 9   adults                          85913 non-null  int64
 10  children                        85913 non-null  float64
 11  meal                            85913 non-null  object
 12  market_segment                  85913 non-null  object
 13  distribution_channel            85913 non-null  object
 14  is_repeated_guest               85913 non-null  int64
 15  previous_cancellations          85913 non-null  int64
 16  previous_bookings_not_canceled  85913 non-null  int64
 17  reserved_room_type              85913 non-null  object
 18  assigned_room_type              85913 non-null  object
 19  booking_changes                 85913 non-null  int64
 20  customer_type                   85913 non-null  object
 21  adr                             85913 non-null  float64
 22  required_car_parking_spaces     85913 non-null  int64
 23  total_of_special_requests       85913 non-null  int64
dtypes: float64(2), int64(14), object(8)
memory usage: 15.7+ MB
None

In [3]:
## Create X (features) and y(response)
X_features = hotel_df.drop('is_canceled', axis=1)
display(X_features.head())
y_target = hotel_df.is_canceled
display(y_target.head())

,hotel,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,customer_type,adr,required_car_parking_spaces,total_of_special_requests
0,Resort Hotel,342,1,July,27,1,0,0,2,0.0,...,0,0,0,C,C,3,Transient,0.0,0,0
1,Resort Hotel,7,1,July,27,1,0,1,1,0.0,...,0,0,0,A,C,0,Transient,75.0,0,0
2,Resort Hotel,13,1,July,27,1,0,1,1,0.0,...,0,0,0,A,A,0,Transient,75.0,0,0
3,Resort Hotel,14,1,July,27,1,0,2,2,0.0,...,0,0,0,A,A,0,Transient,98.0,0,1
4,Resort Hotel,0,1,July,27,1,0,2,2,0.0,...,0,0,0,C,C,0,Transient,107.0,0,0

0    0
1    0
2    0
3    0
4    0
Name: is_canceled, dtype: int64

## List of numerical and categorical columns:

In [4]:
num_int_type = X_features.select_dtypes(include='int64').columns.tolist()
num_float_type = X_features.select_dtypes(include='float64').columns.tolist()

num_type = num_int_type + num_float_type
print("\n\nNumerical Types columns name: \n", num_type)

cat_object_type = X_features.select_dtypes(include='object').columns.tolist()
print("\n\nCategorical Types columns name: \n", cat_object_type)

Numerical Types columns name:
 ['lead_time', 'arrival_date_year', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'required_car_parking_spaces', 'total_of_special_requests', 'children', 'adr']


Categorical Types columns name:
 ['hotel', 'arrival_date_month', 'meal', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'customer_type']

In [5]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_transformer

from sklearn.compose import make_column_transformer
column_trans = make_column_transformer((OneHotEncoder(sparse=False), cat_object_type), 
                                       (StandardScaler(), num_type), remainder = 'passthrough')
# check
column_trans.fit_transform(X_features)

array([[ 0.        ,  1.        ,  0.        , ..., -0.84127719,
        -0.30576108, -1.93632564],
       [ 0.        ,  1.        ,  0.        , ..., -0.84127719,
        -0.30576108, -0.57446615],
       [ 0.        ,  1.        ,  0.        , ..., -0.84127719,
        -0.30576108, -0.57446615],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  3.96874843,
        -0.30576108,  0.92739249],
       [ 1.        ,  0.        ,  0.        , ..., -0.84127719,
        -0.30576108, -0.04061723],
       [ 1.        ,  0.        ,  0.        , ...,  1.56373562,
        -0.30576108,  0.80918309]])

In [6]:
## Splitiing hotel datasets into training and testing datasets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_features, y_target, test_size = 0.3, random_state=0)

In [7]:
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LogisticRegression
from sklearn import svm

logreg_pipe = make_pipeline(column_trans, LogisticRegression())
svm_pipe = make_pipeline(column_trans, svm.SVC())

In [8]:
# from sklearn.model_selection import cross_val_score

# from numpy import nan
# cross_val_score(logreg_pipe, X_train, y_train, cv=3, scoring='accuracy').mean()

In [9]:
logreg_pipe.fit(X_train, y_train)

y_pred = logreg_pipe.predict(X_test)


from sklearn import metrics
print(metrics.accuracy_score(y_test, y_pred))

C:\Users\yrobi\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

0.7864514627143633